# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FiltreDate
                                 A QGIS plugin
 Filtre une couche avec des champs de date de création et de destruction
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-10
        copyright            : (C) 2025 by Wendy Laurent (Ville d'Orléans)
        email                : wendy.laurent@orleans-metropole.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FiltreDate class from file FiltreDate.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Filtre_Date import FiltreDate
    return FiltreDate(iface)
